### PR TITLE
Add Galileo's Middle Finger to list

### PR DESCRIPTION
**Pull request by zachlatta**
To partially address #8 :-).

### CODE REVIEW

**Comment by maxwofford** [comment]
I've been wanting to read this

**Comment by zachlatta** [comment]
I think I can lend you my Kindle copy, if you want it.

**Comment by maxwofford** [comment]
@zachlatta Thanks! Do I need a Kindle to do that?

**Comment by zachlatta** [comment]
You should be able to read it from your phone or web browser.

On Tue, Apr 26, 2016 at 3:37 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Thanks! Do I need a Kindle to
> do that?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/reading-list/pull/9#issuecomment-214908650

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Pull request merged**
